name = "KondoSC"
uuid = "d4509ca9-d502-4e75-ab17-cad5d686a091"
authors = ["Hao Zhang", "Los Alamos National Laboratory"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
